---
repos:
  - repo: https://github.com/psf/black
    rev: 193ee766ca496871f93621d6b58d57a6564ff81b # 23.7.0
    hooks:
      - id: black
        args: [--line-length=120, --quiet]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9 # v4.4.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer
      - id: trailing-whitespace
